version: '3'

services:

  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"

  notes-service:
    build: ./notes-service
    ports:
      - "5002:5002"
    depends_on:
      - auth-service
      - audit-service

  audit-service:
    build: ./audit-service
    ports:
      - "5003:5003"

volumes:
  jenkins_home:
