events {}

http {

    access_log /logs/access.log;
    error_log /logs/error.log;

    server {
	
        listen 80;

        add_header X-Content-Type-Options "nosniff";
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header Cross-Origin-Resource-Policy "same-origin";
        add_header Cache-Control "no-store";

        server_tokens off;

        location = / {
            return 200 'Secure Notes API Running';
        }

        location /auth/ {
            proxy_pass http://auth-service:5001/;
        }

        location /notes/ {
            proxy_pass http://notes-service:5002/;
        }

        location /audit/ {
            proxy_pass http://audit-service:5003/;
        }
    }
}
