events {}

http {

    server {

        listen 80;

        location /auth/ {
            proxy_pass http://auth-service:5001/;
        }

        location /notes/ {
            proxy_pass http://notes-service:5002/;
        }

        location /audit/ {
            proxy_pass http://audit-service:5003/;
        }
    }
}
